package com.cladonia.xngreditor.scenario;

import static org.junit.jupiter.api.Assertions.*;

import java.util.Vector;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

/**
 * Tests for {@link ScenarioProperties} — the configuration object shared by
 * all Transform menu actions: Execute Simple XSLT, Execute Advanced XSLT,
 * Execute FO, Execute XQuery, and Execute Schematron.
 */
class ScenarioPropertiesTest {

    private ScenarioProperties props;

    @BeforeEach
    void setUp() {
        props = new ScenarioProperties();
    }

    // ── Name / ID ──────────────────────────────────────────────

    @Test
    @DisplayName("name round-trips through set/get")
    void nameRoundTrip() {
        props.setName("My Scenario");
        assertEquals("My Scenario", props.getName());
    }

    @Test
    @DisplayName("getID auto-generates a non-null identifier")
    void idAutoGenerated() {
        props.setName("test");
        String id = props.getID();
        assertNotNull(id);
        assertTrue(id.startsWith("SP"));
    }

    // ── Input properties ────────────────────────────────────────

    @Nested
    @DisplayName("Input configuration")
    class InputConfig {
        @Test
        void inputTypeDefaults() {
            // getInteger returns -1 when no value has been set
            assertEquals(-1, props.getInputType());
        }

        @Test
        void inputTypeCurrentDocument() {
            props.setInputType(ScenarioProperties.INPUT_CURRENT_DOCUMENT);
            assertEquals(ScenarioProperties.INPUT_CURRENT_DOCUMENT, props.getInputType());
        }

        @Test
        void inputTypePrompt() {
            props.setInputType(ScenarioProperties.INPUT_PROMPT_FOR_DOCUMENT);
            assertEquals(ScenarioProperties.INPUT_PROMPT_FOR_DOCUMENT, props.getInputType());
        }

        @Test
        void inputFileRoundTrip() {
            props.setInputFile("file:///tmp/test.xml");
            assertEquals("file:///tmp/test.xml", props.getInputURL());
        }
    }

    // ── XSL properties (Execute Simple XSLT / Execute Advanced XSLT) ──

    @Nested
    @DisplayName("XSL configuration (Simple & Advanced XSLT)")
    class XslConfig {
        @Test
        void xslEnabledDefaultsFalse() {
            assertFalse(props.isXSLEnabled());
        }

        @Test
        void xslEnabledToggle() {
            props.setXSLEnabled(true);
            assertTrue(props.isXSLEnabled());
            props.setXSLEnabled(false);
            assertFalse(props.isXSLEnabled());
        }

        @Test
        void xslTypeRoundTrip() {
            props.setXSLType(ScenarioProperties.XSL_FROM_URL);
            assertEquals(ScenarioProperties.XSL_FROM_URL, props.getXSLType());

            props.setXSLType(ScenarioProperties.XSL_CURRENT_DOCUMENT);
            assertEquals(ScenarioProperties.XSL_CURRENT_DOCUMENT, props.getXSLType());

            props.setXSLType(ScenarioProperties.XSL_PROMPT_FOR_DOCUMENT);
            assertEquals(ScenarioProperties.XSL_PROMPT_FOR_DOCUMENT, props.getXSLType());

            props.setXSLType(ScenarioProperties.XSL_USE_PROCESSING_INSTRUCTIONS);
            assertEquals(ScenarioProperties.XSL_USE_PROCESSING_INSTRUCTIONS, props.getXSLType());
        }

        @Test
        void xslUrlRoundTrip() {
            props.setXSLURL("file:///tmp/style.xsl");
            assertEquals("file:///tmp/style.xsl", props.getXSLURL());
        }

        @Test
        void xslSystemIdRoundTrip() {
            props.setXSLSystemId("urn:test:system-id");
            assertEquals("urn:test:system-id", props.getXSLSystemId());
        }
    }

    // ── XQuery properties (Execute XQuery) ───────────────────────

    @Nested
    @DisplayName("XQuery configuration")
    class XQueryConfig {
        @Test
        void xqueryEnabledDefaultsFalse() {
            assertFalse(props.isXQueryEnabled());
        }

        @Test
        void xqueryEnabledToggle() {
            props.setXQueryEnabled(true);
            assertTrue(props.isXQueryEnabled());
        }

        @Test
        void xqueryTypeRoundTrip() {
            props.setXQueryType(ScenarioProperties.XQUERY_FROM_URL);
            assertEquals(ScenarioProperties.XQUERY_FROM_URL, props.getXQueryType());

            props.setXQueryType(ScenarioProperties.XQUERY_CURRENT_DOCUMENT);
            assertEquals(ScenarioProperties.XQUERY_CURRENT_DOCUMENT, props.getXQueryType());

            props.setXQueryType(ScenarioProperties.XQUERY_PROMPT_FOR_DOCUMENT);
            assertEquals(ScenarioProperties.XQUERY_PROMPT_FOR_DOCUMENT, props.getXQueryType());
        }

        @Test
        void xqueryUrlRoundTrip() {
            props.setXQueryURL("file:///tmp/query.xq");
            assertEquals("file:///tmp/query.xq", props.getXQueryURL());
        }
    }

    // ── FOP properties (Execute FO) ──────────────────────────────

    @Nested
    @DisplayName("FOP configuration (Execute FO)")
    class FopConfig {
        @Test
        void fopEnabledDefaultsFalse() {
            assertFalse(props.isFOPEnabled());
        }

        @Test
        void fopEnabledToggle() {
            props.setFOPEnabled(true);
            assertTrue(props.isFOPEnabled());
        }

        @Test
        void fopTypeRoundTrip() {
            props.setFOPType(ScenarioProperties.FOP_TYPE_PDF);
            assertEquals(ScenarioProperties.FOP_TYPE_PDF, props.getFOPType());

            props.setFOPType(ScenarioProperties.FOP_TYPE_PS);
            assertEquals(ScenarioProperties.FOP_TYPE_PS, props.getFOPType());

            props.setFOPType(ScenarioProperties.FOP_TYPE_TXT);
            assertEquals(ScenarioProperties.FOP_TYPE_TXT, props.getFOPType());

            props.setFOPType(ScenarioProperties.FOP_TYPE_SVG);
            assertEquals(ScenarioProperties.FOP_TYPE_SVG, props.getFOPType());
        }

        @Test
        void fopOutputTypeRoundTrip() {
            props.setFOPOutputType(ScenarioProperties.FOP_OUTPUT_TO_FILE);
            assertEquals(ScenarioProperties.FOP_OUTPUT_TO_FILE, props.getFOPOutputType());

            props.setFOPOutputType(ScenarioProperties.FOP_OUTPUT_TO_VIEWER);
            assertEquals(ScenarioProperties.FOP_OUTPUT_TO_VIEWER, props.getFOPOutputType());

            props.setFOPOutputType(ScenarioProperties.FOP_OUTPUT_PROMPT_FOR_FILE);
            assertEquals(ScenarioProperties.FOP_OUTPUT_PROMPT_FOR_FILE, props.getFOPOutputType());
        }

        @Test
        void fopOutputFileRoundTrip() {
            props.setFOPOutputFile("/tmp/output.pdf");
            assertEquals("/tmp/output.pdf", props.getFOPOutputFile());
        }
    }

    // ── Output properties ────────────────────────────────────────

    @Nested
    @DisplayName("Output configuration")
    class OutputConfig {
        @Test
        void outputTypeNewDocument() {
            props.setOutputType(ScenarioProperties.OUTPUT_TO_NEW_DOCUMENT);
            assertEquals(ScenarioProperties.OUTPUT_TO_NEW_DOCUMENT, props.getOutputType());
        }

        @Test
        void outputTypeToFile() {
            props.setOutputType(ScenarioProperties.OUTPUT_TO_FILE);
            assertEquals(ScenarioProperties.OUTPUT_TO_FILE, props.getOutputType());
        }

        @Test
        void outputTypeToInput() {
            props.setOutputType(ScenarioProperties.OUTPUT_TO_INPUT);
            assertEquals(ScenarioProperties.OUTPUT_TO_INPUT, props.getOutputType());
        }

        @Test
        void outputTypeDoNothing() {
            props.setOutputType(ScenarioProperties.OUTPUT_DO_NOTHING);
            assertEquals(ScenarioProperties.OUTPUT_DO_NOTHING, props.getOutputType());
        }

        @Test
        void outputTypePromptForFile() {
            props.setOutputType(ScenarioProperties.OUTPUT_PROMPT_FOR_FILE);
            assertEquals(ScenarioProperties.OUTPUT_PROMPT_FOR_FILE, props.getOutputType());
        }

        @Test
        void outputFileRoundTrip() {
            props.setOutputFile("/tmp/out.xml");
            assertEquals("/tmp/out.xml", props.getOutputFile());
        }

        @Test
        @DisplayName("deprecated output-to-browser (2) upgrades to new-document")
        void deprecatedBrowserType() {
            props.setOutputType(2); // old OUTPUT_TO_BROWSER
            assertEquals(ScenarioProperties.OUTPUT_TO_NEW_DOCUMENT, props.getOutputType());
        }

        @Test
        @DisplayName("deprecated output-to-console (1) upgrades to new-document")
        void deprecatedConsoleType() {
            props.setOutputType(1); // old OUTPUT_TO_CONSOLE
            assertEquals(ScenarioProperties.OUTPUT_TO_NEW_DOCUMENT, props.getOutputType());
        }
    }

    // ── Processor (XSLT engine selection) ────────────────────────

    @Nested
    @DisplayName("Processor configuration")
    class ProcessorConfig {
        @Test
        void processorDefaultsToDefault() {
            assertEquals(ScenarioProperties.PROCESSOR_DEFAULT, props.getProcessor());
        }

        @Test
        void processorXalan() {
            props.setProcessor(ScenarioProperties.PROCESSOR_XALAN);
            assertEquals(ScenarioProperties.PROCESSOR_XALAN, props.getProcessor());
        }

        @Test
        void processorSaxonXslt1() {
            props.setProcessor(ScenarioProperties.PROCESSOR_SAXON_XSLT1);
            assertEquals(ScenarioProperties.PROCESSOR_SAXON_XSLT1, props.getProcessor());
        }

        @Test
        void processorSaxonXslt2() {
            props.setProcessor(ScenarioProperties.PROCESSOR_SAXON_XSLT2);
            assertEquals(ScenarioProperties.PROCESSOR_SAXON_XSLT2, props.getProcessor());
        }
    }

    // ── Browser properties ───────────────────────────────────────

    @Nested
    @DisplayName("Browser configuration")
    class BrowserConfig {
        @Test
        void browserEnabledDefaultsFalse() {
            assertFalse(props.isBrowserEnabled());
        }

        @Test
        void browserEnabledToggle() {
            props.setBrowserEnabled(true);
            assertTrue(props.isBrowserEnabled());
        }

        @Test
        void browserUrlRoundTrip() {
            props.setBrowserURL("http://localhost/output.html");
            assertEquals("http://localhost/output.html", props.getBrowserURL());
        }
    }

    // ── Parameters (used by Advanced XSLT) ───────────────────────

    @Nested
    @DisplayName("Parameters management")
    class ParameterManagement {
        @Test
        void initiallyEmpty() {
            assertTrue(props.getParameters().isEmpty());
        }

        @Test
        void addAndRetrieveParameter() {
            ParameterProperties p = new ParameterProperties("key", "value");
            props.addParameter(p);

            Vector params = props.getParameters();
            assertEquals(1, params.size());
            ParameterProperties result = (ParameterProperties) params.get(0);
            assertEquals("key", result.getName());
            assertEquals("value", result.getValue());
        }

        @Test
        void addMultipleParameters() {
            props.addParameter(new ParameterProperties("a", "1"));
            props.addParameter(new ParameterProperties("b", "2"));
            props.addParameter(new ParameterProperties("c", "3"));

            assertEquals(3, props.getParameters().size());
        }

        @Test
        void removeParameter() {
            ParameterProperties p = new ParameterProperties("key", "value");
            props.addParameter(p);
            assertEquals(1, props.getParameters().size());

            props.removeParameter((ParameterProperties) props.getParameters().get(0));
            assertEquals(0, props.getParameters().size());
        }
    }

    // ── Update (copy from another ScenarioProperties) ────────────

    @Test
    @DisplayName("update() copies all relevant properties")
    void updateCopiesProperties() {
        ScenarioProperties source = new ScenarioProperties();
        source.setInputType(ScenarioProperties.INPUT_CURRENT_DOCUMENT);
        source.setInputFile("file:///input.xml");
        source.setXSLEnabled(true);
        source.setXSLType(ScenarioProperties.XSL_FROM_URL);
        source.setXSLURL("file:///style.xsl");
        source.setProcessor(ScenarioProperties.PROCESSOR_XALAN);
        source.setOutputType(ScenarioProperties.OUTPUT_TO_NEW_DOCUMENT);
        source.setFOPEnabled(false);
        source.addParameter(new ParameterProperties("p1", "v1"));

        props.update(source);

        assertEquals(ScenarioProperties.INPUT_CURRENT_DOCUMENT, props.getInputType());
        assertEquals("file:///input.xml", props.getInputURL());
        assertTrue(props.isXSLEnabled());
        assertEquals(ScenarioProperties.XSL_FROM_URL, props.getXSLType());
        assertEquals("file:///style.xsl", props.getXSLURL());
        assertEquals(ScenarioProperties.PROCESSOR_XALAN, props.getProcessor());
        assertEquals(ScenarioProperties.OUTPUT_TO_NEW_DOCUMENT, props.getOutputType());
        assertEquals(1, props.getParameters().size());
    }

    // ── Export / Import (round-trip through XML) ─────────────────

    @Test
    @DisplayName("export and re-import scenario preserves XSLT settings")
    void exportImportXsltRoundTrip() throws Exception {
        java.net.URL base = new java.net.URL("file:///tmp/scenarios/");

        props.setName("XSLT Test");
        props.setInputType(ScenarioProperties.INPUT_FROM_URL);
        props.setInputFile("file:///tmp/input.xml");
        props.setXSLEnabled(true);
        props.setXSLType(ScenarioProperties.XSL_FROM_URL);
        props.setXSLURL("file:///tmp/style.xsl");
        props.setProcessor(ScenarioProperties.PROCESSOR_SAXON_XSLT2);
        props.setOutputType(ScenarioProperties.OUTPUT_TO_NEW_DOCUMENT);
        props.setFOPEnabled(false);
        props.addParameter(new ParameterProperties("key", "val"));

        com.cladonia.xml.XElement exported = props.exportScenario(base);
        assertNotNull(exported);
        assertEquals("scenario", exported.getName());

        ScenarioProperties reimported = new ScenarioProperties(base, exported);
        assertEquals("XSLT Test", reimported.getName());
        assertTrue(reimported.isXSLEnabled());
        assertEquals(ScenarioProperties.PROCESSOR_SAXON_XSLT2, reimported.getProcessor());
        assertEquals(1, reimported.getParameters().size());
    }

    @Test
    @DisplayName("export and re-import scenario preserves XQuery settings")
    void exportImportXqueryRoundTrip() throws Exception {
        java.net.URL base = new java.net.URL("file:///tmp/scenarios/");

        props.setName("XQuery Test");
        props.setInputType(ScenarioProperties.INPUT_FROM_URL);
        props.setInputFile("file:///tmp/input.xml");
        props.setXSLEnabled(false);
        props.setXQueryEnabled(true);
        props.setXQueryType(ScenarioProperties.XQUERY_FROM_URL);
        props.setXQueryURL("file:///tmp/query.xq");
        props.setOutputType(ScenarioProperties.OUTPUT_TO_NEW_DOCUMENT);
        props.setFOPEnabled(false);

        com.cladonia.xml.XElement exported = props.exportScenario(base);
        ScenarioProperties reimported = new ScenarioProperties(base, exported);

        assertEquals("XQuery Test", reimported.getName());
        assertTrue(reimported.isXQueryEnabled());
        assertFalse(reimported.isXSLEnabled());
    }

    @Test
    @DisplayName("export and re-import scenario preserves FOP settings")
    void exportImportFopRoundTrip() throws Exception {
        java.net.URL base = new java.net.URL("file:///tmp/scenarios/");

        props.setName("FO Test");
        props.setInputType(ScenarioProperties.INPUT_FROM_URL);
        props.setInputFile("file:///tmp/input.xml");
        props.setXSLEnabled(true);
        props.setXSLType(ScenarioProperties.XSL_FROM_URL);
        props.setXSLURL("file:///tmp/fo.xsl");
        props.setFOPEnabled(true);
        props.setFOPType(ScenarioProperties.FOP_TYPE_PDF);
        props.setFOPOutputType(ScenarioProperties.FOP_OUTPUT_TO_FILE);
        props.setFOPOutputFile("/tmp/out.pdf");

        com.cladonia.xml.XElement exported = props.exportScenario(base);
        ScenarioProperties reimported = new ScenarioProperties(base, exported);

        assertEquals("FO Test", reimported.getName());
        assertTrue(reimported.isFOPEnabled());
        assertEquals(ScenarioProperties.FOP_TYPE_PDF, reimported.getFOPType());
    }

    // ── Constant values sanity check ─────────────────────────────

    @Test
    @DisplayName("static constants have expected values")
    void constantsSanity() {
        assertEquals(0, ScenarioProperties.INPUT_FROM_URL);
        assertEquals(1, ScenarioProperties.INPUT_CURRENT_DOCUMENT);
        assertEquals(2, ScenarioProperties.INPUT_PROMPT_FOR_DOCUMENT);

        assertEquals(0, ScenarioProperties.XSL_FROM_URL);
        assertEquals(1, ScenarioProperties.XSL_CURRENT_DOCUMENT);
        assertEquals(2, ScenarioProperties.XSL_PROMPT_FOR_DOCUMENT);
        assertEquals(3, ScenarioProperties.XSL_USE_PROCESSING_INSTRUCTIONS);

        assertEquals(0, ScenarioProperties.PROCESSOR_DEFAULT);
        assertEquals(1, ScenarioProperties.PROCESSOR_XALAN);
        assertEquals(2, ScenarioProperties.PROCESSOR_SAXON_XSLT1);
        assertEquals(3, ScenarioProperties.PROCESSOR_SAXON_XSLT2);

        assertEquals(0, ScenarioProperties.FOP_TYPE_PDF);
        assertEquals(1, ScenarioProperties.FOP_TYPE_PS);
        assertEquals(2, ScenarioProperties.FOP_TYPE_TXT);
        assertEquals(3, ScenarioProperties.FOP_TYPE_SVG);
    }
}
